services:
  web:
    build: .
    container_name: dexcom-web
    restart: unless-stopped
    ports:
      - 8095:5000
    environment:
      - DEXCOM_USER=your_username_here
      - DEXCOM_PASS=your_password_here
      - DEXCOM_OUS=False
      - TZ=America/New_York
    # ADD THIS SECTION BELOW:
    volumes:
      - ./:/app
    networks:
      - dexcom-net
networks:
  dexcom-net:
    driver: bridge
